dist: trusty
sudo: false
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '11'
  - '12'
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libfontconfig1
      - libgconf-2-4
      - libnss3
      - libstdc++6
install: "npm install"
script: "./test-driver.sh"
