version: 1.0.{build}
environment:
  matrix:
  - nodejs_version: 6
  - nodejs_version: 8
  - nodejs_version: 9
  - nodejs_version: 10
install:
- ps: >-
    Install-Product node $env:nodejs_version

    npm install
build: off
test_script:
- ps: >-
    $nodeProcess = start node bin\chromedriver -PassThru

    sleep 5

    if ($nodeProcess.HasExited) { exit 1 }

    Stop-Process -Id $nodeProcess.Id -Force